DROP TABLE IF EXISTS JR_IMDA.IMBA_DWS.SEGAMAKER_OUTPUT;
CREATE TABLE JR_IMDA.IMBA_DWS.SEGAMAKER_OUTPUT AS (
WITH 
CTE1 AS (
	SELECT u1.*, u2.USER_TOTAL_PRODUCTS, u2.USER_DISTINCT_PRODUCTS , u2.USER_REORDER_RATIO 
	FROM JR_IMDA.IMBA_DWM.USER_FEATURE_1 u1
	JOIN JR_IMDA.IMBA_DWM.USER_FEATURE_2 u2
	ON u1.USER_ID = u2.USER_ID),
CTE2 AS (
	SELECT uf.*, pf.PROD_ORDERS, pf.PROD_REORDERS, pf.PROD_FIRST_ORDERS, pf.PROD_SECOND_ORDERS
	FROM JR_IMDA.IMBA_DWM.UP_FEATURES uf
	JOIN JR_IMDA.IMBA_DWM.PRD_FEATURES  pf
	ON uf.PRODUCT_ID  = pf.PRODUCT_ID)
SELECT CTE1.*, CTE2.PRODUCT_ID, CTE2.UP_ORDERS, CTE2.UP_FIRST_ORDER, CTE2.UP_LAST_ORDER, CTE2.UP_AVERAGE_CART_POSITION, CTE2.PROD_ORDERS, CTE2.PROD_REORDERS, CTE2.PROD_FIRST_ORDERS, CTE2.PROD_SECOND_ORDERS
FROM CTE1
JOIN CTE2
ON CTE1.USER_ID = CTE2.USER_ID
)
