CREATE OR REPLACE FILE FORMAT  "JR_IMDA"."IMBA_DB"."SEGAMAKER_INPUT" TYPE = 'PARQUET' COMPRESSION = 'AUTO' BINARY_AS_TEXT = TRUE;

create or replace stage "JR_IMDA"."IMBA_DB"."MY_STAGE_SAGEMAKER" URL = 's3://chunhe01/imba_data/segamaker_input' 
CREDENTIALS = (AWS_KEY_ID = 'AKIA46NOBBKEZBSJ4K5F' AWS_SECRET_KEY = 'vteUgt1OnTr/iR5CbeJjOmiLiuqZ6EpNGAvGbKUR')
FILE_format = "JR_IMDA"."IMBA_DB"."SEGAMAKER_INPUT";

COPY INTO @"JR_IMDA"."IMBA_DB"."MY_STAGE_SAGEMAKER"
FROM (SELECT *
	FROM JR_IMDA.IMBA_DWS.SEGAMAKER_OUTPUT 
	) SINGLE = FALSE
	OVERWRITE=TRUE