USE JR_IMDA.IMBA_DB;

DROP TABLE IF EXISTS AISLES;

CREATE STAGE IF NOT EXISTS "JR_IMDA"."IMBA_DB".AISLES_TABLE URL = 's3://chunhe01/imba_data/aisles.csv' 
CREDENTIALS = (AWS_KEY_ID = 'AKIA46NOBBKEZBSJ4K5F' AWS_SECRET_KEY = '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');

CREATE TABLE IF NOT EXISTS "JR_IMDA"."IMBA_DB"."AISLES" 
("AISLE_ID" INTEGER NOT NULL, 
"AISLE" STRING NOT NULL) 
COMMENT = 'This table shows product type';

copy into JR_IMDA.IMBA_DB.AISLES
from @AISLES_TABLE
file_format = FILE_FORMAT_1_NO_COMPRESS;