USE JR_IMDA.IMBA_DB;

DROP TABLE IF EXISTS DEPARTMENTS;

CREATE STAGE IF NOT EXISTS "JR_IMDA"."IMBA_DB".DEPARTMENTS_STAGE URL = 's3://chunhe01/imba_data/departments.csv' 
CREDENTIALS = (AWS_KEY_ID = 'AKIA46NOBBKEZBSJ4K5F' AWS_SECRET_KEY = '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');

CREATE TABLE IF NOT EXISTS JR_IMDA.IMBA_DB.DEPARTMENTS
("DEPARTMENT_ID" INTEGER NOT NULL, 
"DEPARTMENT" STRING NOT NULL) 
COMMENT = 'This table shows product departments';

copy into JR_IMDA.IMBA_DB.DEPARTMENTS
from @DEPARTMENTS_STAGE
file_format = FILE_FORMAT_1_NO_COMPRESS;
