USE JR_IMDA.IMBA_DB;

DROP TABLE IF EXISTS ORDERS;

CREATE STAGE IF NOT EXISTS "JR_IMDA"."IMBA_DB".ORDERS_STAGE URL = 's3://chunhe01/imba_data/orders.csv' 
CREDENTIALS = (AWS_KEY_ID = 'AKIA46NOBBKEZBSJ4K5F' AWS_SECRET_KEY = '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');

CREATE TABLE IF NOT EXISTS "JR_IMDA"."IMBA_DB"."ORDERS" 
("ORDER_ID" INTEGER NOT NULL, 
"USER_ID" INTEGER NOT NULL, 
"EVAL_SET" String NOT NULL, 
"ORDER_NUMBER" INTEGER NOT NULL, 
"ORDER_DOW" INTEGER NOT NULL, 
"ORDER_HOUR_OF_DAY" INTEGER NOT NULL, 
"DAYS_SINCE_PRIOR_ORDER" INTEGER) 
COMMENT = 'For order history';

copy into JR_IMDA.IMBA_DB.ORDERS
from @ORDERS_STAGE
file_format = FILE_FORMAT_1_NO_COMPRESS;


