USE JR_IMDA.IMBA_DB;

DROP TABLE IF EXISTS ORDERS;

CREATE STAGE IF NOT EXISTS  "JR_IMDA"."IMBA_DB".PRODUCTS_STAGE URL = 's3://chunhe01/imba_data/products.csv' 
CREDENTIALS = (AWS_KEY_ID = 'AKIA46NOBBKEZBSJ4K5F' AWS_SECRET_KEY = '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');

CREATE TABLE IF NOT EXISTS  "JR_IMDA"."IMBA_DB"."PRODUCTS" 
("PRODUCT_ID" INTEGER NOT NULL, 
"PRODUCT_NAME" String NOT NULL, 
"AISLES_ID" INTEGER NOT NULL, 
"DEPARTMENT_ID" INTEGER NOT NULL ) 
COMMENT = 'For products details';

copy into JR_IMDA.IMBA_DB.PRODUCTS
from @products_stage
file_format = FILE_FORMAT_1_NO_COMPRESS;
