USE JR_IMDA.IMBA_DB;

DROP TABLE IF EXISTS ORDER_PRODUCTS_PRIOR;

CREATE STAGE IF NOT EXISTS  "JR_IMDA"."IMBA_DB".ORDER_PRODUCTS_PRIOR_STAGE URL = 's3://chunhe01/imba_data/order_products__prior.csv.gz' 
CREDENTIALS = (AWS_KEY_ID = 'AKIA46NOBBKEZBSJ4K5F' AWS_SECRET_KEY = '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');

CREATE TABLE IF NOT EXISTS "JR_IMDA"."IMBA_DB"."ORDER_PRODUCTS_PRIOR" 
("ORDER_ID" INTEGER NOT NULL, 
"PRODUCT_ID" INTEGER NOT NULL, 
"ADD_TO_CART_ORDER"INTEGER NOT NULL,
"REORDERED" INTEGER NOT NULL) 
COMMENT = 'Order_Prior';

copy into JR_IMDA.IMBA_DB.ORDER_PRODUCTS_PRIOR
from @ORDER_PRODUCTS_PRIOR_STAGE
file_format = FILE_FORMAT_2_COMPRESS;
