DROP TABLE IF EXISTS JR_IMDA.IMBA_ODS.ORDERS_PRIOR;
CREATE TABLE JR_IMDA.IMBA_ODS.ORDERS_PRIOR AS (
SELECT o.*, opr.product_id, opr.add_to_cart_order, opr.reordered
FROM JR_IMDA.IMBA_DB.ORDER_PRODUCTS_PRIOR opr
JOIN JR_IMDA.IMBA_DB.ORDERS o
ON opr.ORDER_ID = o.ORDER_ID
WHERE o.EVAL_SET = 'prior' 
)
