DROP TABLE IF EXISTS JR_IMDA.IMBA_ODS.ORDERS_TRAIN;
CREATE TABLE JR_IMDA.IMBA_ODS.ORDERS_TRAIN AS (
SELECT o.*, opt.product_id, opt.add_to_cart_order, opt.reordered
FROM JR_IMDA.IMBA_DB.ORDER_PRODUCTS_TRAIN  opt
JOIN JR_IMDA.IMBA_DB.ORDERS o
ON opt.ORDER_ID = o.ORDER_ID
WHERE o.EVAL_SET = 'train' 
)
