CREATE DATABASE IF NOT EXISTS JR_IMDA;
USE JR_IMDA;

-- 1. CREATAE SCHEMA IMBA FOR RESTORE THE RAW DATA
-- 1.1 DATA IS SOTRED IN AMAZON S3 ORGINALLY
-- 1.2 FOR DB LAYER, IT RESOTRES OLTP DATA
CREATE SCHEMA IF NOT EXISTS IMBA_DB;

-- 2 CREATE SCHEMA IMBA_ODS
-- 2.1 THE DATA IS GENERATED FROM STAGE OF IMBA
-- 2.2 THIS STAGE RESTORED COMBINED AND UNIONED DATA FOR FURTHER USAGE
-- 2.3 FOR THIS LAYER, DATA FOR PRODUCTS_PRIOR/TRAIN HAS BEEN Unioned and FILLTERED WITH ORDERS  
CREATE SCHEMA IF NOT EXISTS IMBA_ODS;

-- 3 CREATE SCHEMA IMBA_DWD
-- 3.1 FOR THIS LAYER, WE EWOULD LIKE TO CLEAR DATA
-- 3.1.1 CLEAR METHDOLOGY 
-- DROP NA FOR USER_ID
-- DROP NA FOR ORDER_ID
-- DELETE ABNORMAL DATA
-- CURRENT DATA SET HAS CLEAR AND TIDY DATA, SO THAT THIS LAYER IS OMMITED FOR CURRENT PROJECT
CREATE SCHEMA IF NOT EXISTS IMBA_DWD;

-- 4 CREATE SCHEMA IMBA_DWM
-- 4.1 FOR THIS LAYER, WE WOULD LIKE TO AGGREGATE AND CREATE FEATURE FILES
CREATE SCHEMA IF NOT EXISTS IMBA_DWM;

-- 5. CREATE SCHEMA IMBA_DWS
-- 5.1 FOR THIS LAYER, WE WOULD LIKE TO HAVE A WIDE TABLE FOR DATA SCIENCNTIST USAGEG
CREATE SCHEMA IF NOT EXISTS IMBA_DWS;

-- 6. CREATE SCHEMA IMBA_DM
-- 6.1 DATA FOR THIS TABLE IS USED FOR REPORTING VISUALISATION
CREATE SCHEMA IF NOT EXISTS IMBA_DM;
